gateways:
  tobiko-cloud:
      connection:
        type: databricks
        server_hostname: "{{ env_var('DATABRICKS_TEST_HOST') }}"
        http_path: "{{ env_var('DATABRICKS_TEST_PATH') }}"
        access_token: "{{ env_var('DATABRICKS_TEST_TOKEN') }}"
        catalog: tpcdi

default_gateway: tobiko-cloud

model_defaults:
  dialect: databricks

variables:
  raw_schema: tpcdi_100_dbsql_100
  catalog: tpcdi
  